routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::get('/admin/2017', 'AdminController@index');
Route::get('/auth/register', 'Auth\RegisterController@getRegister');
Route::post('/auth/register', 'Auth\RegisterController@register');
Route::post('/auth/login', 'Auth\RegisterController@login');
Route::group(['middleware' => 'roles', 'roles' => ['super_admin', 'admin']], function () {
    Route::get('/category', 'CategoryController@getCategory');
    Route::POST('/category_store', 'CategoryController@createCategory');
    Route::get('/subcategory', 'CategoryController@getSubcategory');
    Route::POST('/subcategory_store', 'CategoryController@createSubCategory');
    Route::POST('/subcategory/brand', 'CategoryController@getBrand');


    Route::get('/brand', 'BrandController@index');
    Route::POST('/brand_store', 'BrandController@create');

    Route::get('/product', 'ProductController@index');
    Route::get('/product.create', 'ProductController@create');
    Route::POST('/product_store', 'ProductController@store');
    Route::get('/product/{id}', 'ProductController@productView');

    Route::POST('/product_ajaxAction', 'ProductController@ajaxAction');

    Route::get('supplier', 'SupplierController@index');
    Route::POST('supplier_store', 'SupplierController@store');
    Route::get('supplier_create', 'SupplierController@create');

    Route::Post('/stock_in', 'StockInController@stockIn');


    Route::get('/color', 'ColorController@index');
    Route::POST('/color_store', 'ColorController@store');

    Route::get('/size', 'SizeController@index');
    Route::POST('/size_store', 'SizeController@store');

    Route::PUT('/states', 'StatesController@states');

    Route::get('/pictur/{id}', 'PicturController@index');
    Route::post('/pictur.store', 'PicturController@store');
    Route::post('/pictur_viewPictur', 'PicturController@viewPictur');
});
Route::post('/customer/register', 'CustomerController@register');
Route::post('/customer/login', 'CustomerController@login');
Route::get('/customer/logout', 'CustomerController@logout');
Route::get('/customer/create', 'CustomerController@create');




Route::get('/order/checkout', 'ChackOutController@checkOut');
Route::POST('/order', 'ChackOutController@order');
Route::get('/payment/{id}', 'ChackOutController@payment');
Route::POST('/payment/store/{id}', 'ChackOutController@store');



Route::get('/', 'PagesController@home');
Route::get('/details/{id}', 'PagesController@product_details');
Route::get('/shop', 'PagesController@shop');
Route::POST('/picture/view', 'PagesController@pictureView');
Route::POST('/qty/view', 'PagesController@qtyView');

Route::resource('/cart', 'CartController');

resources/views/partial/_footer.blade.php
<footer id="footer"><!--Footer-->
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-8 ">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2017 My shop Inc. All rights reserved.</p>
					<p class="pull-right">Made by <span><a target="_blank" href="http://www.rowjat.com">Mohammad Rowjat Ullah</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->

resources/views/partial/_header.blade.php
<header id="header"><!--header-->

    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a href="{{url('/')}}"><img src="{{asset('asset/images/home/logo.png')}}" alt="" /></a>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="{{route('cart.index')}}"><i class="fa fa-shopping-cart"></i> Cart
                                    @if(Cart::count()>0)
                                    <span class="badge" style="background: #ff9900">{{Cart::count()}}</span>
                                    @endif
                                </a>
                            </li>
                            @if(Auth::check())

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-arrow-circle-up"></span>&nbsp; {{Auth::check()?auth()->user()->name:''}} <span class="caret"></span></a>
                                <ul class="dropdown-menu">

                                    <li><a href="#">Orders</a></li><br/>

                                    <li role="separator" class="divider"></li><br/>
                                    <li><a href="#">Profile</a></li><br/>
                                    <li><a href="{{url('/customer/logout')}}">Logout</a></li><br/>
                                </ul>
                            </li>

                            @else
                            <li><a href="{{url('/order/checkout')}}"><i class="fa fa-lock"></i> Login</a></li>
                            @endif
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->
</header>

resources/views/partial/_sidebar.blade.php
<div class="left-sidebar">
    <h2>Category</h2>
    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
        @foreach($categories as $category)
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">

                    @if($category->subCategory->count() >0)
                    
                    <a data-toggle="collapse" data-parent="#accordian" href="#{{$category->name}}">
                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                        {{$category->name}}

                    </a>
                    @else
                    <a href="{{url('shop?cat='.$category->id)}}">{{$category->name}}</a>
                    @endif
                </h4>
            </div>
            @if($category->subCategory->count() >0)
            <div id="{{$category->name}}" class="panel-collapse collapse">
                <div class="panel-body">

                    <ul>
                        @foreach($category->subCategory->where('states',1) as $sub)
                        <li><a href="{{url('shop?subCat='.$sub->id)}}">{{$sub->name}} </a></li>
                        @endforeach
                    </ul>

                </div>
            </div>
            @endif

        </div>
        @endforeach

    </div><!--/category-products-->

    <div class="brands_products"><!--brands_products-->
        <h2>Brands</h2>
        <div class="brands-name">
            <ul class="nav nav-pills nav-stacked">
                @foreach($brands as $brand)
                <li><a href="{{url('shop?brand='.$brand->id)}}"><img src="{{asset('/asset/admin/images/brand/'.$brand->logo)}}" alt="" width="15" height="15"/> <span class="pull-right">({{App\Product::where('states',1)->where('brand_id',$brand->id)->count()}})</span>{{$brand->name}}</a></li>
                @endforeach
            </ul>
        </div>
    </div><!--/brands_products-->

    <!--    <div class="price-range">price-range
            <h2>Price Range</h2>
            <div class="well text-center">
                <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="1000" data-slider-step="5" data-slider-value="[0,450]" id="sl2" ><br />
                <b class="pull-left">$ 0</b> <b class="pull-right">$ 1000</b>
            </div>
        </div>/price-range-->

    <div class="shipping text-center">
        <img src="{{asset('asset/images/home/shipping.jpg')}}" alt="" />
    </div>

</div>